name: Package

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [master]

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          VERSION=$(echo 'refs/tags/v0.0.2' | sed -e "s#refs/tags/v##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "filename=$REPOSITORY-$VERSION" >> $GITHUB_OUTPUT

      - name: Set git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update manifest version
        run: |
          jq '.version="${{ steps.version.outputs.version }}"' public/manifest.json > tmp
          mv tmp public/manifest.json

      - name: Update package version
        run: |
          jq '.version="${{ steps.version.outputs.version }}"' package.json > tmp
          mv tmp package.json

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Cat manifest.json and package.json
        run: |
          cat dist/manifest.json
          cat package.json

      - name: Push version changes
        run: |
          git add public/manifest.json package.json
          git commit -m "chore: Bump up v${{ steps.version.outputs.version }}"
          git push

      - name: Check package
        run: cat package.json

      - name: Packaging
        run: zip -r ${{ steps.version.outputs.filename }}.zip dist

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: ${{ steps.version.outputs.filename }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
