name: Package

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/v##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "filename=$REPOSITORY-$VERSION" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and build
        run: |
          npm ci
          npm run build

      - name: Packaging
        run: zip -r ${{ steps.version.outputs.filename }}.zip dist

      - name: "Build changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## ✨ New features",
                    "labels": ["newfeatures"]
                },
                {
                    "title": "## 🩹 Improvements & Bug fixes",
                    "labels": ["improvement", "bug"]
                },
                {
                    "title": "## 📦 Others",
                    "labels": ["documentation", "dependencies"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: ${{ steps.version.outputs.filename }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # AMOはmanifest.jsonがzipのルートに必要なため、dist内をzip化する
      - name: Packaging for Firefox Add-ons
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          (cd dist && zip -r ../${{ steps.version.outputs.filename }}-firefox.zip .)
          git archive --format=zip --output=${{ steps.version.outputs.filename }}-source.zip HEAD

      - name: Upload to Firefox Add-ons
        if: startsWith(github.ref, 'refs/tags/v')
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ekitan-trainno-display@aoisupersix.github.io
          xpi-path: ${{ steps.version.outputs.filename }}-firefox.zip
          source-file-path: ${{ steps.version.outputs.filename }}-source.zip
          license: MIT
          jwt-issuer: ${{ secrets.AMO_JWT_ISSUER }}
          jwt-secret: ${{ secrets.AMO_JWT_SECRET }}
